---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: travisdb
    box: ubuntu-1604-xenial
    machine_type: f1-micro
    zone: europe-west1-b
    tags: puma-server
provisioner:
  name: ansible
  options:
    vvv: false
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
